package com.sjtu.webapp.form;

import com.sjtu.webapp.form.BaseForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="addressForm"
 */
public class AddressForm extends BaseForm implements java.io.Serializable {

	protected String address;

	protected String city;

	protected String province;

	protected String country;

	protected String postalCode;

	/** Default empty constructor. */
	public AddressForm() {
	}

	public String getAddress() {
		return this.address;
	}

	/**
	 */

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvince() {
		return this.province;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCountry() {
		return this.country;
	}

	/**
	 * @struts.validator type="required"
	 */

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	/**
	 * @struts.validator type="required"
	 * @struts.validator type="mask" msgkey="errors.zip"
	 * @struts.validator-var name="mask" value="${zip}"
	 */

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-AddressForm.java containing the additional code and place it in
	 * your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false

	}

}
