package com.sjtu.admin.webapp.form;

import com.sjtu.webapp.form.BaseForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="midCatalogForm"
 */
public class MidCatalogForm extends BaseForm implements java.io.Serializable {

	protected String midCatalogId;

	protected String midCatalogName;

	protected String largeCatalogId;

	/** Default empty constructor. */
	public MidCatalogForm() {
	}

	public String getMidCatalogId() {
		return this.midCatalogId;
	}

	/**
	 */

	public void setMidCatalogId(String midCatalogId) {
		this.midCatalogId = midCatalogId;
	}

	public String getMidCatalogName() {
		return this.midCatalogName;
	}

	/**
	 */

	public void setMidCatalogName(String midCatalogName) {
		this.midCatalogName = midCatalogName;
	}

	/**
	 * @return the largeCatalogId
	 */
	public String getLargeCatalogId() {
		return largeCatalogId;
	}

	/**
	 * @param largeCatalogId
	 *            the largeCatalogId to set
	 */
	public void setLargeCatalogId(String largeCatalogId) {
		this.largeCatalogId = largeCatalogId;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-MidCatalogForm.java containing the additional code and place it
	 * in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false
		this.largeCatalogId = null;
		this.midCatalogId = null;
		this.midCatalogName = null;

	}

}
