package com.sjtu.admin.webapp.form;

import com.sjtu.webapp.form.BaseForm;
import org.apache.struts.action.ActionMapping;

import javax.servlet.http.HttpServletRequest;

/**
 * Generated by XDoclet/actionform. This class can be further processed with
 * XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 * 
 * @struts.form name="smallCatalogForm"
 */
public class SmallCatalogForm extends BaseForm implements java.io.Serializable {

	protected String smallCatalogId;

	protected String smallCatalogName;
	protected String midCatalogId;

	/** Default empty constructor. */
	public SmallCatalogForm() {
	}

	public String getSmallCatalogId() {
		return this.smallCatalogId;
	}

	/**
	 */

	public void setSmallCatalogId(String smallCatalogId) {
		this.smallCatalogId = smallCatalogId;
	}

	public String getSmallCatalogName() {
		return this.smallCatalogName;
	}

	/**
	 */

	public void setSmallCatalogName(String smallCatalogName) {
		this.smallCatalogName = smallCatalogName;
	}

	/**
	 * @return the midCatalogId
	 */
	public String getMidCatalogId() {
		return midCatalogId;
	}

	/**
	 * @param midCatalogId
	 *            the midCatalogId to set
	 */
	public void setMidCatalogId(String midCatalogId) {
		this.midCatalogId = midCatalogId;
	}

	/*
	 * To add non XDoclet-generated methods, create a file named
	 * xdoclet-SmallCatalogForm.java containing the additional code and place it
	 * in your metadata/web directory.
	 */
	/**
	 * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
	 *      javax.servlet.http.HttpServletRequest)
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// reset any boolean data types to false
		this.midCatalogId = null;
		this.smallCatalogId = null;
		this.smallCatalogName = null;

	}

}
